---
- block: # Drop configuration templates
  - name: Drop grafana server configuration
    template:
      src: grafana-server.j2
      dest: "{{ grafana_environment_filepath }}"
      owner: "{{ grafana_user }}"
      group: "{{ grafana_group }}"
      mode: 0644
    notify: Restart Grafana Server Service

  - name: Drop grafana ini configuration
    template:
      src: grafana.ini.j2
      dest: "{{ grafana_config_filepath }}"
      owner: "{{ grafana_user }}"
      group: "{{ grafana_group }}"
      mode: 0644
    notify: Restart Grafana Server Service

  - meta: flush_handlers


- name: Ensure {{ grafana_service_name }} service started and start up at boot
  service:
    name: "{{ grafana_service_name }}"
    state: started
    enabled: yes
    daemon_reload: yes
