---
- name: Add grafana repository key
  apt_key:
    url: "{{ grafana_apt_key_url }}"
    id: "{{ grafana_apt_key_id }}"

- name: Add grafana apt-repository
  apt_repository:
    repo: "{{ grafana_apt_repo }}"

- name: Ensure directory created
  file:
    path: "{{ item }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: 0755
    state: directory
  with_items:
    - "{{ grafana_dir_home }}"
    - "{{ grafana_dir_log }}"
    - "{{ grafana_dir_data }}"
    - "{{ grafana_dir_config }}"
    - "{{ grafana_dir_plugins }}"
