---
- name: Include OS family specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - default.yml

- include: influxdb_pre.yml
- include: influxdb_install.yml

- include: influxdb_post.yml
  tags:
    - configuration
    - drop-config

- include: influxdb_credential.yml
  tags:
    - credential
    - user

- include: influxdb_database.yml
  tags:
    - database
    - create-database
