---
- name: Include OS family specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - default.yml

- include: grafana_pre.yml
- include: grafana_install.yml

- include: grafana_post.yml
  tags:
    - configuration
    - drop-config

- include: grafana_database.yml
  tags:
    - database
    - create-database
